### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by keiespro** [kevinGodell/mse-live-player#6]
It works perfect on desktop, but not working on mobile.
Any advice?

**Comment by kevinGodell** [comment]
Unfortunately, media source extensions is not supported by iOS and may not be supported by android, therefore mse live player will not be able to work on mobile. An alternative for iOS would be to use jpeg via socket or native hls. You can try out my ffmpeg-streamer tool to see what will work in your mobile browser. https://github.com/kevinGodell/ffmpeg-streamer
